kind: pipeline
type: docker
name: default

steps:
# - name: start-notify
#   image: plugins/slack
#   settings:
#     webhook: https://hooks.slack.com/services/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
#     channel: cicd
#     template: >
#         Build {{build.number}} of {{build.branch}} started. {{build.link}}
- name: build
  image: alpine
  commands:
  - echo "hello always"
- name: publish
  image: alpine
  commands:
    - echo "echo publish"
- name: deploy
  image: docker
  commands:
  - echo "echo deploy"
# - name: end-notify
#   image: plugins/slack
#   settings:
#     webhook: https://hooks.slack.com/services/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
#     channel: cicd
#     template: >
#       {{#success build.status}}
#         Build {{build.number}} of {{build.branch}} successful. {{build.link}}
#       {{else}}
#         Build {{build.number}} of {{build.branch}} failed. Please fix!. {{build.link}}
#       {{/success}}
# volumes:
# - name: docker
#   host:
#     path: /var/run/docker.sock      